baseURL: https://thoughtseer.github.io/
languageCode: en-us
title: ThoughtSeer's CTF Blog
theme: "PaperMod"

params:
    profileMode:
        enabled: true
        title: "ThoughtSeer"
        subtitle: "A CTF Blog"
        imageUrl: "/assets/ts.png" # optional
        imageTitle: "ThoughtSeer Logo" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Archive
              url: "/archive"
            - name: Github
              url: "https://github.com/thoughtseer"

    socialIcons: # optional
        - name: "Twitter"
          url: "<link>"
        - name: "Twitch"
          url: "<link2>"
